version: "3.9"

services:
  mysql_starwars:
    image: mysql
    container_name: mysql_starwars
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - starwars-network
    mem_limit: 512m
    mem_reservation: 512m
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - starwars-data:/var/lib/mysql
    restart: always

  starwars-app:
    image: starwars-app
    container_name: starwars-app
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - starwars-network
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql_starwars
    restart: always

  nginx:
    image: nginx
    container_name: starwars-nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - starwars-app
    restart: always
    networks:
      - starwars-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  starwars-network:
    driver: bridge

volumes:
  starwars-data:
    driver: local